
[2024-12-13 15:59:40,875] ERROR: Exception on /entry [POST]
Traceback (most recent call last):
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\thread-site\vulnerability_codes\src\app.py", line 105, in entry
    db.execute(sql)
sqlite3.OperationalError: unrecognized token: ""<scrIpt>alert(1);</scRipt>', '2024-12-13', 'ZAP', 'zaproxy@example.com', 'ZAP');"

[2024-12-13 15:59:40,897] ERROR: 
500 Error occurred at endpoint 'entry'
---URL---
http://127.0.0.1:5000/entry
---Method---
POST
---Error---
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
---GET Parameters---
{}
---Form Parameters---
name: '"<scrIpt>alert(1);</scRipt>
birthday: 2024-12-13
email: zaproxy@example.com
user_id: ZAP
password1: ZAP
password2: ZAP
---SQL---
INSERT INTO user_list (name, birthday, user_id, email, pass) VALUES (''"<scrIpt>alert(1);</scRipt>', '2024-12-13', 'ZAP', 'zaproxy@example.com', 'ZAP');

[2024-12-13 16:00:11,364] ERROR: Exception on /entry [POST]
Traceback (most recent call last):
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\thread-site\vulnerability_codes\src\app.py", line 105, in entry
    db.execute(sql)
sqlite3.OperationalError: unrecognized token: ""<script>alert(1);</script>', '2024-12-13', 'ZAP', 'zaproxy@example.com', 'ZAP');"

[2024-12-13 16:00:11,373] ERROR: 
500 Error occurred at endpoint 'entry'
---URL---
http://127.0.0.1:5000/entry
---Method---
POST
---Error---
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
---GET Parameters---
{}
---Form Parameters---
name: '"<script>alert(1);</script>
birthday: 2024-12-13
email: zaproxy@example.com
user_id: ZAP
password1: ZAP
password2: ZAP
---SQL---
INSERT INTO user_list (name, birthday, user_id, email, pass) VALUES (''"<script>alert(1);</script>', '2024-12-13', 'ZAP', 'zaproxy@example.com', 'ZAP');

[2024-12-13 16:00:44,561] ERROR: Exception on /entry [POST]
Traceback (most recent call last):
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\kshotsu1.IXAS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\thread-site\vulnerability_codes\src\app.py", line 105, in entry
    db.execute(sql)
sqlite3.OperationalError: near ";": syntax error

[2024-12-13 16:00:44,570] ERROR: 
500 Error occurred at endpoint 'entry'
---URL---
http://127.0.0.1:5000/entry
---Method---
POST
---Error---
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
---GET Parameters---
{}
---Form Parameters---
name: '<script>alert(1);</script>
birthday: 2024-12-13
email: zaproxy@example.com
user_id: ZAP
password1: ZAP
password2: ZAP
---SQL---
INSERT INTO user_list (name, birthday, user_id, email, pass) VALUES (''<script>alert(1);</script>', '2024-12-13', 'ZAP', 'zaproxy@example.com', 'ZAP');
